import { randomBytes } from "node:crypto";
import type { Url } from "../../generated/prisma/client";
import { env } from "../lib/env";
import { AlreadyExistsError } from "../lib/errors";
import { prisma } from "../lib/prisma";

/**
 * Generates a cryptographically secure random slug
 * @param length - The desired length of the slug (default: 8)
 * @returns A random slug using base64url encoding
 */
function generateSlug(length = 8): string {
    return randomBytes(Math.ceil(length * 0.75))
        .toString("base64url")
        .slice(0, length);
}

/**
 * Generates the full short URL for a given URL record
 * @param url - The URL record
 * @returns The full short URL
 */
export function shortUrl(url: Url): string {
    return `${env.HTTPS ? "https" : "http"}://${env.HOSTNAME}/${url.slug}`;
}

/**
 * Ensures a unique slug is generated by retrying on collisions
 * @param slug - Optional initial slug to try (if not provided, a random slug will be generated)
 * @param maxRetries - Maximum number of retry attempts (default: 10)
 * @returns A unique slug
 * @throws {Error} If unable to generate unique slug after max retries
 */
export async function ensureUniqueSlug(slug?: string): Promise<string> {
    const candidate = slug ?? generateSlug();
    const existing = await prisma.url.findUnique({
        where: { slug: candidate },
    });
    if (!existing) return candidate;
    throw new AlreadyExistsError(
        slug
            ? `Slug "${slug}" already exists`
            : "Generated slug collision, please try again",
    );
}
