import { randomBytes } from "node:crypto";
import type { Url } from "../../generated/prisma/client";
import { env } from "../lib/env";
import {
    AlreadyExistsError,
    ExpiryTooLargeError,
    ForbiddenError,
    NotFoundError,
} from "../lib/errors";
import { prisma } from "../lib/prisma";

export { ExpiryTooLargeError, ForbiddenError, NotFoundError };

export type CreateUrlInput = {
    longUrl: string;
    userId: string;
    ttl?: number;
    expiresAt?: Date;
    slug?: string;
};

/**
 * Generates a cryptographically secure random slug
 * @param length - The desired length of the slug (default: 8)
 * @returns A random slug using base64url encoding
 */
function generateSlug(length = 8): string {
    return randomBytes(Math.ceil(length * 0.75))
        .toString("base64url")
        .slice(0, length);
}

/**
 * Generates the full short URL for a given URL record
 * @param url - The URL record
 * @returns The full short URL
 */
function shortUrl(url: Url): string {
    return `${env.HTTPS ? "https" : "http"}://${env.HOSTNAME}/${url.slug}`;
}

/**
 * Ensures a unique slug is generated by retrying on collisions
 * @param slug - Optional initial slug to try (if not provided, a random slug will be generated)
 * @param maxRetries - Maximum number of retry attempts (default: 10)
 * @returns A unique slug
 * @throws {Error} If unable to generate unique slug after max retries
 */
async function ensureUniqueSlug(slug?: string): Promise<string> {
    const candidate = slug ?? generateSlug();
    const existing = await prisma.url.findUnique({
        where: { slug: candidate },
    });
    if (!existing) return candidate;
    throw new AlreadyExistsError(
        slug
            ? `Slug "${slug}" already exists`
            : "Generated slug collision, please try again",
    );
}

/**
 * Resolves the expiry date from input parameters
 * @param input - The URL creation input containing optional ttl or expiresAt
 * @returns The calculated expiry date
 * @throws {ExpiryTooLargeError} If expiry exceeds MAX_EXPIRY_SECONDS
 */
function resolveExpiry(input: CreateUrlInput): Date {
    const maxSeconds = env.MAX_EXPIRY_SECONDS;
    const maxDate = new Date(Date.now() + maxSeconds * 1000);

    if (input.expiresAt) {
        if (input.expiresAt > maxDate) {
            throw new ExpiryTooLargeError(maxSeconds);
        }
        return input.expiresAt;
    }

    if (input.ttl) {
        if (input.ttl > maxSeconds) {
            throw new ExpiryTooLargeError(maxSeconds);
        }
        return new Date(Date.now() + input.ttl * 1000);
    }

    return new Date(Date.now() + maxSeconds * 1000); // Default expiry if none provided
}

/**
 * Checks if a URL has expired
 * @param url - The URL record to check
 * @returns true if the URL has expired, false otherwise
 */
function isExpired(url: Url): boolean {
    return url.expiresAt !== null && url.expiresAt < new Date();
}

/**
 * Creates a new shortened URL with optional expiry
 * @param input - The URL creation parameters
 * @returns The created URL record
 * @throws {ExpiryTooLargeError} If the expiry exceeds MAX_EXPIRY_SECONDS
 * @throws {Error} If unable to generate unique slug after retries
 */
export async function createUrl(
    input: CreateUrlInput,
): Promise<Url & { shortUrl: string }> {
    const slug = await ensureUniqueSlug(input.slug);
    const expiresAt = resolveExpiry(input);

    const url = await prisma.url.create({
        data: {
            slug,
            longUrl: input.longUrl,
            userId: input.userId,
            expiresAt,
        },
    });

    return {
        ...url,
        shortUrl: shortUrl(url),
    };
}

/**
 * Resolves a slug to its URL and increments the click counter
 * Deletes the URL if it has expired
 * @param slug - The short slug to resolve
 * @returns The URL record or null if not found or expired
 */
export async function resolveUrl(slug: string): Promise<string | null> {
    const url = await prisma.url.findUnique({ where: { slug } });
    if (!url) return null;

    if (isExpired(url)) {
        await prisma.url.delete({ where: { slug } });
        return null;
    }

    const updatedUrl = await prisma.url.update({
        where: { slug },
        data: { clicks: { increment: 1 } },
    });
    return updatedUrl.longUrl;
}

/**
 * Lists all non-expired URLs for a user
 * @param userId - The user ID to filter by
 * @returns Array of URL records ordered by creation date (newest first)
 */
export async function listUrls(
    userId: string,
    orderBy: "createdAt" | "expiresAt" | "clicks" = "createdAt",
    order: "asc" | "desc" = "desc",
): Promise<(Url & { shortUrl: string })[]> {
    const urls = await prisma.url.findMany({
        where: {
            userId,
            OR: [{ expiresAt: null }, { expiresAt: { gte: new Date() } }],
        },
        orderBy: {
            [orderBy]: order,
        },
    });

    return urls.map((url) => ({
        ...url,
        shortUrl: shortUrl(url),
    }));
}

export async function deleteAllUrls(userId: string): Promise<number> {
    const { count } = await prisma.url.deleteMany({ where: { userId } });
    return count;
}

/**
 * Gets a single URL by slug with ownership verification
 * Deletes the URL if it has expired
 * @param slug - The short slug to look up
 * @param userId - The user ID for ownership verification
 * @returns The URL record
 * @throws {NotFoundError} If URL not found or expired
 * @throws {ForbiddenError} If user doesn't own the URL
 */
export async function getUrl(
    slug: string,
    userId: string,
): Promise<Url & { shortUrl: string }> {
    const url = await prisma.url.findUnique({ where: { slug } });

    if (!url) throw new NotFoundError();

    if (isExpired(url)) {
        await prisma.url.delete({ where: { slug } });
        throw new NotFoundError();
    }

    if (url.userId !== userId) throw new ForbiddenError();

    return {
        ...url,
        shortUrl: shortUrl(url),
    };
}

/**
 * Deletes a URL by slug with ownership verification
 * @param slug - The short slug to delete
 * @param userId - The user ID for ownership verification
 * @throws {NotFoundError} If URL not found
 * @throws {ForbiddenError} If user doesn't own the URL
 */
export async function deleteUrl(
    slug: string,
    userId: string,
): Promise<undefined> {
    const url = await prisma.url.findUnique({ where: { slug } });

    if (!url) throw new NotFoundError();
    if (url.userId !== userId) throw new ForbiddenError();

    await prisma.url.delete({ where: { slug } });
}

/**
 * Deletes all expired URLs (used by background cron job)
 * @returns The number of deleted URLs
 */
export async function deleteExpiredUrls(): Promise<number> {
    const result = await prisma.url.deleteMany({
        where: {
            expiresAt: {
                lt: new Date(),
            },
        },
    });
    return result.count;
}
