name: Docker

on:
  pull_request:
  push:
  workflow_call:

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp .env.example .env
      - name: Build dev image
        run: docker compose build

  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp .env.example .env
      - name: Build prod image
        run: docker compose -f docker-compose.prod.yaml build
